default_install_hook_types: [pre-commit]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      # Run the formatter.
      - id: ruff-format
